#!/bin/sh
#valime mida backuppida
echo "Palun sisestage kataloog, mida soovite backuppida"
read backup
sleep 1
echo "Palun sisestage mida soovite panna backupi nimeks"
read BACKUP_NAME
sleep 1
#alustame backuppimisega
d=$(date --iso) #võtame kuupäeva
backup=$BACKUP_NAME"_"$d".tar.gz" #anname laiendid
tar -czvf ./$backup ~
echo "korras"
ls -l
