#!/bin/sh
#valime mida backuppida
echo "Palun sisestage kataloog, mida soovite backuppida"
read backup
echo "andke katalooginimi"
read baasnimeke
sleep 1
#võtame baasnime...
echo "Palun oodake..."
baasnimi="$(basename -- $baasnimeke)" #võtame kataloginimelise baasnime
sleep 1
#alustame backuppimisega
d=$(date --iso) #võtame kuupäeva
backup=$baasnimi"_"$d".tar.gz" #anname laiendid
backup_kaust=/home/user/skriptimine/praks4a/backup/
tar -zcvf $backup $backup_kaust
echo "Tehtud!"
