#!/bin/sh
#algus
echo "sisesta kuu number: ";read kuu
if test $kuu -eq 12 -o $kuu -eq 1 -o $kuu -eq 2
then
echo "Praegu on talv"
elif test $kuu -ge 3 -a $kuu -le 5
then
echo "Praegu on kevad"
elif test $kuu -ge 6 -a $kuu -le 8
then
echo "Praegu on suvi"
elif test $kuu -ge 9 -a $kuu -le 11
then
echo "Praegu on talv"
elif test $kuu -ge 13 -o $kuu -le 0
then
echo "Sellist kuud ei ole kalendris kuid ehk tulevikus on..."
fi
