#!bin/bash
#skript2
#algus
who | cut -f1 -d" " | cut -f2 -d"." > perenimi # lõikab perenime ja salvestab
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi # lõikab eesnime ja salvestab
paste -d"."  perenimi eesnimi > nimed #kokku paneb
cat nime | sort | uniq # sorteerib väljundi ja korduvad eemaldab
#skripti lõpp
